# Generated by Django 6.0.2 on 2026-02-21 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('healthy_week_badges', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CookedRecipeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(blank=True, null=True)),
                ('recipe_name', models.CharField(max_length=255)),
                ('cooked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('vegetable_servings', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooked_recipe_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'cooked_at'], name='nutrition_c_user_id_344e66_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyNutritionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('total_vegetable_servings', models.FloatField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('balanced', models.BooleanField(default=False)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_nutrition_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='nutrition_d_user_id_c0105c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NutritionRewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('cook_log', 'Cook Log'), ('daily_balance', 'Daily Balance'), ('streak_bonus', 'Streak Bonus'), ('healthy_week_badge', 'Healthy Week Badge'), ('level_up', 'Level Up')], max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('reference_date', models.DateField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'awarded_at'], name='nutrition_n_user_id_318595_idx'), models.Index(fields=['user', 'event_type', 'reference_date'], name='nutrition_n_user_id_1b539c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyNutritionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('average_score', models.FloatField(default=0)),
                ('days_tracked', models.PositiveSmallIntegerField(default=0)),
                ('balanced_days', models.PositiveSmallIntegerField(default=0)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('total_vegetable_servings', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_nutrition_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'week_start'], name='nutrition_w_user_id_11174f_idx')],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
