# Generated by Django 6.0.1 on 2026-01-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Vegetable", "Vegetable"),
                            ("Fruit", "Fruit"),
                            ("Meat", "Meat"),
                            ("Dairy", "Dairy"),
                            ("Grain", "Grain"),
                            ("Spice", "Spice"),
                            ("Oil", "Oil"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("default_unit", models.CharField(max_length=20)),
            ],
        ),
    ]
