# Generated by Django 6.0.1 on 2026-01-28 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_ingredient_category_pantryitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("user", "ingredient")},
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("Vegetable", "Vegetable"),
                    ("Fruit", "Fruit"),
                    ("Meat", "Meat"),
                    ("Dairy", "Dairy"),
                    ("Grain", "Grain"),
                    ("Spice", "Spice"),
                    ("Oil", "Oil"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="created_at",
        ),
    ]
