# Generated by Django 6.0.1 on 2026-02-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventoryitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
