# Generated by Django 6.0.1 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_ingredient_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="pantryitem",
            name="low_stock_limit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
