# Generated by Django 6.0.1 on 2026-03-20 15:00

import django.db.models.deletion
from django.db import migrations, models


def seed_pantry_batches(apps, schema_editor):
    PantryItem = apps.get_model("inventory", "PantryItem")
    PantryItemBatch = apps.get_model("inventory", "PantryItemBatch")

    for item in PantryItem.objects.all().iterator():
        if float(item.quantity or 0.0) <= 0:
            continue
        if PantryItemBatch.objects.filter(pantry_item_id=item.id).exists():
            continue
        PantryItemBatch.objects.create(
            pantry_item_id=item.id,
            quantity=item.quantity,
            expiry_date=item.expiry_date,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_pantryitem_low_stock_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PantryItemBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.FloatField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pantry_item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="inventory.pantryitem"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pantryitembatch",
            index=models.Index(fields=["pantry_item", "expiry_date"], name="inv_pantry_batch_exp_idx"),
        ),
        migrations.RunPython(seed_pantry_batches, migrations.RunPython.noop),
    ]
