# Generated by Django 6.0.2 on 2026-03-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_pantryitembatch"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pantryitembatch",
            new_name="inventory_p_pantry__34910a_idx",
            old_name="inv_pantry_batch_exp_idx",
        ),
    ]
