# Generated by Django 6.0.1 on 2026-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("shopowner", "Shop Owner")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
