# Generated by Django 6.0.1 on 2026-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("shopowner", "Shop Owner"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
