# Generated by Django 6.0.1 on 2026-01-29 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Millilitre"),
                    ("l", "Litre"),
                    ("pcs", "Pieces"),
                    ("pack", "Pack"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"profile__role": "shopowner"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
