# Generated by Django 6.0.1 on 2026-02-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventoryitem_unique_together_and_more"),
        ("shop", "0003_alter_product_owner_cart_order_orderitem_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="pack_size",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="pack_unit",
            field=models.CharField(default="pcs", max_length=10),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                help_text="Which pantry ingredient this product should update on delivery",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pack_size",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="pack_unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Millilitre"),
                    ("l", "Litre"),
                    ("pcs", "Pieces"),
                    ("pack", "Pack"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"userprofile__role": "shopowner"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
