# Generated by Django 6.0.1 on 2026-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orderitem_pack_size_orderitem_pack_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
