# Generated by Django 6.0.1 on 2026-02-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "PLACED"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                    ("DELIVERED", "DELIVERED"),
                    ("COMPLETED", "COMPLETED"),
                    ("CANCELLED", "CANCELLED"),
                    ("REFUNDED", "REFUNDED"),
                ],
                default="PLACED",
                max_length=20,
            ),
        ),
    ]
