# Generated by Django 6.0.1 on 2026-03-14 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_low_stock_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "PLACED"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("PACKED", "PACKED"),
                    ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                    ("DELIVERED", "DELIVERED"),
                    ("COMPLETED", "COMPLETED"),
                    ("CANCELLED", "CANCELLED"),
                    ("REFUNDED", "REFUNDED"),
                ],
                default="PLACED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShopProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(blank=True, max_length=160)),
                ("address", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        help_text="Store hours e.g. 9 AM - 9 PM",
                        max_length=120,
                    ),
                ),
                (
                    "delivery_radius_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="shops/logos/"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="shops/banners/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        limit_choices_to={"userprofile__role": "shopowner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("SALE", "Sale"),
                            ("REFUND", "Refund"),
                            ("BULK", "Bulk Upload"),
                        ],
                        default="ADJUSTMENT",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
