# Generated by Django 6.0.2 on 2026-03-16 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_cancellation_reason_order_refund_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('HIDDEN', 'HIDDEN')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('shop_owner', models.ForeignKey(limit_choices_to={'userprofile__role': 'shopowner'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
